/* main.c generated by valac 0.56.17, the Vala compiler
 * generated from main.vala, do not modify */

#include <wayland-server-core.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

#define _wl_display_destroy0(var) ((var == NULL) ? NULL : (var = (wl_display_destroy (var), NULL)))

static void _vala_main (void);

static void
_vala_main (void)
{
	struct wl_display* display = NULL;
	struct wl_display* _tmp0_;
	_tmp0_ = wl_display_create ();
	display = _tmp0_;
	_wl_display_destroy0 (display);
}

int
main (int argc,
      char ** argv)
{
	_vala_main ();
	return 0;
}

